import { Component, OnInit, OnDestroy } from '@angular/core';
import { IonicPage, NavParams, Events } from 'ionic-angular';
import { SocialSharing } from '@ionic-native/social-sharing'
import { EventService } from './event.service'
import { ApplicationService } from '../../shared/services/application.service';
import { GlobalService } from '../../shared/services/global.service';

import * as moment from 'moment'

@IonicPage()
@Component({
   selector: 'page-event',
   templateUrl: 'event.html'
})
export class EventPage implements OnInit, OnDestroy {
   title: string = "Evento"
   selectedMembers:any
   toggleMode:boolean= false;
   editMode: boolean = false
   dayKeys:any
   evt: any

   constructor(
      private navParams: NavParams,
      private appSrv: ApplicationService,
      private globalSrv: GlobalService,
      private evtSrv: EventService,
      private socialSharing: SocialSharing
   ) {
      console.log('EventPage constructor');
   }
   ngOnDestroy() {
      console.warn('EventPage destroy');
   }
   ngOnInit(): void {
      console.log('EventPage init');
      this.evt = this.navParams.get('evt')
      this.editMode = (this.evt.creationDate === undefined)
      this.evt.members = [
         {
            username: 'Pablo', onoff: true, days: {
               'LU': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 1 },
                  { hour: 14, value: 1 },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 1 },
                  { hour: 20, value: 1 },
                  { hour: 21, value: 1 },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ],
               'MA': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 0, members: [] },
                  { hour: 20, value: 0, members: [] },
                  { hour: 21, value: 0, members: [] },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ],
               'MI': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 0, members: [] },
                  { hour: 20, value: 0, members: [] },
                  { hour: 21, value: 0, members: [] },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ],
               'JU': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 0, members: [] },
                  { hour: 20, value: 0, members: [] },
                  { hour: 21, value: 0, members: [] },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ],
               'VI': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 0, members: [] },
                  { hour: 20, value: 0, members: [] },
                  { hour: 21, value: 0, members: [] },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ],
               'SA': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 0, members: [] },
                  { hour: 20, value: 0, members: [] },
                  { hour: 21, value: 0, members: [] },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ],
               'DO': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 0, members: [] },
                  { hour: 20, value: 0, members: [] },
                  { hour: 21, value: 0, members: [] },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ]
            }
         },
         {
            username: 'Lucas', onoff: false, days: {
               'LU': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 0, members: [] },
                  { hour: 20, value: 0, members: [] },
                  { hour: 21, value: 0, members: [] },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ],
               'MA': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 0, members: [] },
                  { hour: 20, value: 0, members: [] },
                  { hour: 21, value: 0, members: [] },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ],
               'MI': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 0, members: [] },
                  { hour: 20, value: 0, members: [] },
                  { hour: 21, value: 0, members: [] },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ],
               'JU': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 0, members: [] },
                  { hour: 20, value: 0, members: [] },
                  { hour: 21, value: 0, members: [] },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ],
               'VI': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 1 },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 1 },
                  { hour: 20, value: 1 },
                  { hour: 21, value: 1 },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ],
               'SA': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 1 },
                  { hour: 9, value: 1 },
                  { hour: 10, value: 1 },
                  { hour: 11, value: 1 },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 1 },
                  { hour: 20, value: 1 },
                  { hour: 21, value: 1 },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ],
               'DO': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 0, members: [] },
                  { hour: 20, value: 0, members: [] },
                  { hour: 21, value: 0, members: [] },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ]
            }
         },
         {
            username: 'Fernanado', onoff: false, days: {
               'LU': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 0, members: [] },
                  { hour: 20, value: 0, members: [] },
                  { hour: 21, value: 0, members: [] },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ],
               'MA': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 0, members: [] },
                  { hour: 20, value: 0, members: [] },
                  { hour: 21, value: 0, members: [] },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ],
               'MI': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 0, members: [] },
                  { hour: 20, value: 0, members: [] },
                  { hour: 21, value: 0, members: [] },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ],
               'JU': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 0, members: [] },
                  { hour: 20, value: 0, members: [] },
                  { hour: 21, value: 0, members: [] },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ],
               'VI': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 0, members: [] },
                  { hour: 20, value: 0, members: [] },
                  { hour: 21, value: 0, members: [] },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ],
               'SA': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 1 },
                  { hour: 9, value: 1 },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 1 },
                  { hour: 20, value: 1 },
                  { hour: 21, value: 1 },
                  { hour: 22, value: 1 },
                  { hour: 23, value: 0, members: [] }
               ],
               'DO': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 0, members: [] },
                  { hour: 20, value: 0, members: [] },
                  { hour: 21, value: 0, members: [] },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ]
            }
         },
         {
            username: 'Mariana', onoff: false, days: {
               'LU': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 1 },
                  { hour: 9, value: 1 },
                  { hour: 10, value: 1 },
                  { hour: 11, value: 1 },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 0, members: [] },
                  { hour: 20, value: 0, members: [] },
                  { hour: 21, value: 0, members: [] },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ],
               'MA': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 1 },
                  { hour: 20, value: 1 },
                  { hour: 21, value: 1 },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ],
               'MI': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 1 },
                  { hour: 8, value: 1 },
                  { hour: 9, value: 1 },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 0, members: [] },
                  { hour: 20, value: 0, members: [] },
                  { hour: 21, value: 0, members: [] },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ],
               'JU': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 0, members: [] },
                  { hour: 20, value: 0, members: [] },
                  { hour: 21, value: 0, members: [] },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ],
               'VI': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 1 },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 1 },
                  { hour: 20, value: 1 },
                  { hour: 21, value: 1 },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ],
               'SA': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 1 },
                  { hour: 9, value: 1 },
                  { hour: 10, value: 1 },
                  { hour: 11, value: 1 },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 1 },
                  { hour: 20, value: 1 },
                  { hour: 21, value: 1 },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ],
               'DO': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 1 },
                  { hour: 19, value: 1 },
                  { hour: 20, value: 1 },
                  { hour: 21, value: 1 },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ]
            }
         },
         {
            username: 'Juan', onoff: false, days: {
               'LU': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 1 },
                  { hour: 9, value: 1 },
                  { hour: 10, value: 1 },
                  { hour: 11, value: 1 },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 0, members: [] },
                  { hour: 20, value: 0, members: [] },
                  { hour: 21, value: 0, members: [] },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ],
               'MA': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 0, members: [] },
                  { hour: 20, value: 0, members: [] },
                  { hour: 21, value: 0, members: [] },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ],
               'MI': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 0, members: [] },
                  { hour: 20, value: 0, members: [] },
                  { hour: 21, value: 0, members: [] },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ],
               'JU': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 0, members: [] },
                  { hour: 20, value: 0, members: [] },
                  { hour: 21, value: 0, members: [] },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ],
               'VI': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 0, members: [] },
                  { hour: 20, value: 1 },
                  { hour: 21, value: 1 },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ],
               'SA': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 1 },
                  { hour: 9, value: 1 },
                  { hour: 10, value: 1 },
                  { hour: 11, value: 1 },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 1 },
                  { hour: 20, value: 1 },
                  { hour: 21, value: 1 },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ],
               'DO': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 0, members: [] },
                  { hour: 20, value: 0, members: [] },
                  { hour: 21, value: 0, members: [] },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ]
            }
         },
         {
            username: 'Pato', onoff: false, days: {
               'LU': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 0, members: [] },
                  { hour: 20, value: 0, members: [] },
                  { hour: 21, value: 0, members: [] },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ],
               'MA': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 0, members: [] },
                  { hour: 20, value: 0, members: [] },
                  { hour: 21, value: 0, members: [] },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ],
               'MI': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 0, members: [] },
                  { hour: 20, value: 0, members: [] },
                  { hour: 21, value: 0, members: [] },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ],
               'JU': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 0, members: [] },
                  { hour: 20, value: 0, members: [] },
                  { hour: 21, value: 0, members: [] },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ],
               'VI': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 1 },
                  { hour: 20, value: 1 },
                  { hour: 21, value: 1 },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ],
               'SA': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 0, members: [] },
                  { hour: 20, value: 1 },
                  { hour: 21, value: 1 },
                  { hour: 22, value: 1 },
                  { hour: 23, value: 0, members: [] }
               ],
               'DO': [
                  { hour: 0, value: 0, members: [] },
                  { hour: 1, value: 0, members: [] },
                  { hour: 2, value: 0, members: [] },
                  { hour: 3, value: 0, members: [] },
                  { hour: 4, value: 0, members: [] },
                  { hour: 5, value: 0, members: [] },
                  { hour: 6, value: 0, members: [] },
                  { hour: 7, value: 0, members: [] },
                  { hour: 8, value: 0, members: [] },
                  { hour: 9, value: 0, members: [] },
                  { hour: 10, value: 0, members: [] },
                  { hour: 11, value: 0, members: [] },
                  { hour: 12, value: 0, members: [] },
                  { hour: 13, value: 0, members: [] },
                  { hour: 14, value: 0, members: [] },
                  { hour: 15, value: 0, members: [] },
                  { hour: 16, value: 0, members: [] },
                  { hour: 17, value: 0, members: [] },
                  { hour: 18, value: 0, members: [] },
                  { hour: 19, value: 0, members: [] },
                  { hour: 20, value: 0, members: [] },
                  { hour: 21, value: 0, members: [] },
                  { hour: 22, value: 0, members: [] },
                  { hour: 23, value: 0, members: [] }
               ]
            }
         }
      ]
      /*********************
       *** EVENTOS ***
       [
          {
             id : "343523523423",
             owner : "23432532534",
             eventName: "Reunion de Consorcio",
             description: "Reunion Besares 3950",
             creationDate: 12325524324,
             modDate: 12324142155,
             estimatedDate: 1231231342432,
             members: [
               {
                   idUser:123231321, 
                   data: [
                     {day:"180522", hours:[9,10,11,18,19,20]},
                     {day:"180525", hours:[19,20]},
                     {day:"180522", hours:[9,10,11]}
                     ]
               },
               {
                   idUser:2424242,
                   data: [
                     {day:"180522", hours:[18,19,20]},
                     {day:"180525", hours:[20]},
                     {day:"180527", hours:[10,11]}
                     ]
               },
               {
                   idUser:987654545677,
                   data: [
                     {day:"180523", hours:[18,19,20]},
                     {day:"180525", hours:[20]}
                     ]
               },
               {
                   idUser:443332,
                   data: [
                     {day:"180522", hours:[19,20,21,22]}
                     ]
               },
               {
                   idUser:43433222,
                   data: []
               }
             ]
          }
       ]


       *** USUARIOS ***
       [
          {
             id : "343523523423",
             mail:"ponic12@gmail.com",
             username: "ponic12",
             name: "Pablo"
             avatar: "http://google.com/sdfs34332434",
             events:[
               "343534335354353",
               "454934343434343",
               "354543333344422"
             ]
         },
        {
             id : "343523523423",
             mail:"patriciagonzalezvillar@gmail.com",
             username: "patriciagonzalezvillar",
             name: "Pato"
             avatar: "http://google.com/sdfs34332434",
             events:[
               "993930309380111",
               "454934343434343"
             ]
         },         
      **********************/
      this.evt.data = ""
   }
   toggleMember(ev,u) {
     this.checkEditMode()
     this.processDays()
   }
   onKeyEvent(event) {
      if (event.keyCode == 13) {
         //this.editEventNameFlag = false
      }
   }
   onKeyUser(event) {
      if (event.keyCode == 13) {
         //this.editMode = false
      }
   }
   availability(username){
      if (!this.selectedMembers) return
      const res = !(this.selectedMembers.indexOf(username) == -1)
      return res
   }
   selection(ev){
      if (this.toggleMode == true)
         ev.hr.value = 1 - ev.hr.value
      else
         this.selectedMembers = ev.hr.members
   }

   addContact(){

   }
   share() {
      this.socialSharing.canShareVia('Whatsapp').then(() => {
         this.socialSharing.shareViaWhatsApp('Invitacion a evento!', 'http://www.clarin.com').then(() => {
            this.appSrv.message('Aviso', 'Se ha enviado notificacion a evento!')
         }).catch(() => {
            this.appSrv.message('Error', 'No posee Whatsapp')
         })
      })

      // this.socialSharing.canShareViaEmail().then(() => {
      //    // Sharing via email is possible
      // }).catch(() => {
      //    // Sharing via email is not possible
      // });

      // // Share via email
      // this.socialSharing..shareViaEmail('Body', 'Subject', ['recipient@example.org']).then(() => {
      //    // Success!
      // }).catch(() => {
      //    // Error!
      // });
   }

   private checkEditMode(){
      let cnt = 0
      this.evt.members.forEach(m => {
         if (m.onoff == true)
            cnt = cnt +1
      });
      this.toggleMode = ((cnt == 1) && (this.evt.members[0].onoff == true))
   }
   private processDays() {
      this.resetDays(this.evt.days)
      this.dayKeys = Object.keys(this.evt.days)
      this.evt.members.forEach(member => {
         if (member.onoff === true) {
            this.dayKeys.forEach((key) => {
               this.evt.days[key].forEach((hr, i) => {
                  let x = member.days[key][i].value
                  hr.value = hr.value + x
                  if (x > 0)
                     hr.members.push(member.username)
               })
            });
         }
      });
   }
   private resetDays(days){
      const emptyDays = {
         'LU': [
            { hour: 0, value: 0, members: [] },
            { hour: 1, value: 0, members: [] },
            { hour: 2, value: 0, members: [] },
            { hour: 3, value: 0, members: [] },
            { hour: 4, value: 0, members: [] },
            { hour: 5, value: 0, members: [] },
            { hour: 6, value: 0, members: [] },
            { hour: 7, value: 0, members: [] },
            { hour: 8, value: 0, members: [] },
            { hour: 9, value: 0, members: [] },
            { hour: 10, value: 0, members: [] },
            { hour: 11, value: 0, members: [] },
            { hour: 12, value: 0, members: [] },
            { hour: 13, value: 0, members: [] },
            { hour: 14, value: 0, members: [] },
            { hour: 15, value: 0, members: [] },
            { hour: 16, value: 0, members: [] },
            { hour: 17, value: 0, members: [] },
            { hour: 18, value: 0, members: [] },
            { hour: 19, value: 0, members: [] },
            { hour: 20, value: 0, members: [] },
            { hour: 21, value: 0, members: [] },
            { hour: 22, value: 0, members: [] },
            { hour: 23, value: 0, members: [] }
         ],
         'MA': [
            { hour: 0, value: 0, members: [] },
            { hour: 1, value: 0, members: [] },
            { hour: 2, value: 0, members: [] },
            { hour: 3, value: 0, members: [] },
            { hour: 4, value: 0, members: [] },
            { hour: 5, value: 0, members: [] },
            { hour: 6, value: 0, members: [] },
            { hour: 7, value: 0, members: [] },
            { hour: 8, value: 0, members: [] },
            { hour: 9, value: 0, members: [] },
            { hour: 10, value: 0, members: [] },
            { hour: 11, value: 0, members: [] },
            { hour: 12, value: 0, members: [] },
            { hour: 13, value: 0, members: [] },
            { hour: 14, value: 0, members: [] },
            { hour: 15, value: 0, members: [] },
            { hour: 16, value: 0, members: [] },
            { hour: 17, value: 0, members: [] },
            { hour: 18, value: 0, members: [] },
            { hour: 19, value: 0, members: [] },
            { hour: 20, value: 0, members: [] },
            { hour: 21, value: 0, members: [] },
            { hour: 22, value: 0, members: [] },
            { hour: 23, value: 0, members: [] }
         ],
         'MI': [
            { hour: 0, value: 0, members: [] },
            { hour: 1, value: 0, members: [] },
            { hour: 2, value: 0, members: [] },
            { hour: 3, value: 0, members: [] },
            { hour: 4, value: 0, members: [] },
            { hour: 5, value: 0, members: [] },
            { hour: 6, value: 0, members: [] },
            { hour: 7, value: 0, members: [] },
            { hour: 8, value: 0, members: [] },
            { hour: 9, value: 0, members: [] },
            { hour: 10, value: 0, members: [] },
            { hour: 11, value: 0, members: [] },
            { hour: 12, value: 0, members: [] },
            { hour: 13, value: 0, members: [] },
            { hour: 14, value: 0, members: [] },
            { hour: 15, value: 0, members: [] },
            { hour: 16, value: 0, members: [] },
            { hour: 17, value: 0, members: [] },
            { hour: 18, value: 0, members: [] },
            { hour: 19, value: 0, members: [] },
            { hour: 20, value: 0, members: [] },
            { hour: 21, value: 0, members: [] },
            { hour: 22, value: 0, members: [] },
            { hour: 23, value: 0, members: [] }
         ],
         'JU': [
            { hour: 0, value: 0, members: [] },
            { hour: 1, value: 0, members: [] },
            { hour: 2, value: 0, members: [] },
            { hour: 3, value: 0, members: [] },
            { hour: 4, value: 0, members: [] },
            { hour: 5, value: 0, members: [] },
            { hour: 6, value: 0, members: [] },
            { hour: 7, value: 0, members: [] },
            { hour: 8, value: 0, members: [] },
            { hour: 9, value: 0, members: [] },
            { hour: 10, value: 0, members: [] },
            { hour: 11, value: 0, members: [] },
            { hour: 12, value: 0, members: [] },
            { hour: 13, value: 0, members: [] },
            { hour: 14, value: 0, members: [] },
            { hour: 15, value: 0, members: [] },
            { hour: 16, value: 0, members: [] },
            { hour: 17, value: 0, members: [] },
            { hour: 18, value: 0, members: [] },
            { hour: 19, value: 0, members: [] },
            { hour: 20, value: 0, members: [] },
            { hour: 21, value: 0, members: [] },
            { hour: 22, value: 0, members: [] },
            { hour: 23, value: 0, members: [] }
         ],
         'VI': [
            { hour: 0, value: 0, members: [] },
            { hour: 1, value: 0, members: [] },
            { hour: 2, value: 0, members: [] },
            { hour: 3, value: 0, members: [] },
            { hour: 4, value: 0, members: [] },
            { hour: 5, value: 0, members: [] },
            { hour: 6, value: 0, members: [] },
            { hour: 7, value: 0, members: [] },
            { hour: 8, value: 0, members: [] },
            { hour: 9, value: 0, members: [] },
            { hour: 10, value: 0, members: [] },
            { hour: 11, value: 0, members: [] },
            { hour: 12, value: 0, members: [] },
            { hour: 13, value: 0, members: [] },
            { hour: 14, value: 0, members: [] },
            { hour: 15, value: 0, members: [] },
            { hour: 16, value: 0, members: [] },
            { hour: 17, value: 0, members: [] },
            { hour: 18, value: 0, members: [] },
            { hour: 19, value: 0, members: [] },
            { hour: 20, value: 0, members: [] },
            { hour: 21, value: 0, members: [] },
            { hour: 22, value: 0, members: [] },
            { hour: 23, value: 0, members: [] }
         ],
         'SA': [
            { hour: 0, value: 0, members: [] },
            { hour: 1, value: 0, members: [] },
            { hour: 2, value: 0, members: [] },
            { hour: 3, value: 0, members: [] },
            { hour: 4, value: 0, members: [] },
            { hour: 5, value: 0, members: [] },
            { hour: 6, value: 0, members: [] },
            { hour: 7, value: 0, members: [] },
            { hour: 8, value: 0, members: [] },
            { hour: 9, value: 0, members: [] },
            { hour: 10, value: 0, members: [] },
            { hour: 11, value: 0, members: [] },
            { hour: 12, value: 0, members: [] },
            { hour: 13, value: 0, members: [] },
            { hour: 14, value: 0, members: [] },
            { hour: 15, value: 0, members: [] },
            { hour: 16, value: 0, members: [] },
            { hour: 17, value: 0, members: [] },
            { hour: 18, value: 0, members: [] },
            { hour: 19, value: 0, members: [] },
            { hour: 20, value: 0, members: [] },
            { hour: 21, value: 0, members: [] },
            { hour: 22, value: 0, members: [] },
            { hour: 23, value: 0, members: [] }
         ],
         'DO': [
            { hour: 0, value: 0, members: [] },
            { hour: 1, value: 0, members: [] },
            { hour: 2, value: 0, members: [] },
            { hour: 3, value: 0, members: [] },
            { hour: 4, value: 0, members: [] },
            { hour: 5, value: 0, members: [] },
            { hour: 6, value: 0, members: [] },
            { hour: 7, value: 0, members: [] },
            { hour: 8, value: 0, members: [] },
            { hour: 9, value: 0, members: [] },
            { hour: 10, value: 0, members: [] },
            { hour: 11, value: 0, members: [] },
            { hour: 12, value: 0, members: [] },
            { hour: 13, value: 0, members: [] },
            { hour: 14, value: 0, members: [] },
            { hour: 15, value: 0, members: [] },
            { hour: 16, value: 0, members: [] },
            { hour: 17, value: 0, members: [] },
            { hour: 18, value: 0, members: [] },
            { hour: 19, value: 0, members: [] },
            { hour: 20, value: 0, members: [] },
            { hour: 21, value: 0, members: [] },
            { hour: 22, value: 0, members: [] },
            { hour: 23, value: 0, members: [] }
         ]
      }
      this.evt.days = emptyDays
   }
}
